version: '3.9'

services:
  mysql:
    platform: linux/x86_64
    container_name: mysql_container
    image: mysql:8.0.24
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./sql:/docker-entrypoint-initdb.d/
  
  cache:
    image: redis:latest
    ports:
      - $REDIS_PORT:$REDIS_PORT
    command: redis-server --save 20 1 --loglevel warning
    restart: always
  
  # Node api services:
  api:
    build:
      context: ../nonsense
      dockerfile: Dockerfile
    container_name: api_container
    ports:
      - 3000:3000 
    depends_on:
      - mysql
      - cache 
    env_file: .env
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    restart: always

volumes:
  mysql-volume: {}

